"""Project store for managing agent-generated artifacts.

This module provides Git-based version control for project artifacts.
Each project is stored as a Git repository with automatic commits.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import git
from git import Repo

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class ProjectStore:
    """Git-based project store for agent artifacts.

    Features:
    - Automatic Git repository initialization
    - Version control for all artifacts
    - Branch management for different development streams
    - Commit history for rollback
    """

    def __init__(self, projects_root: Optional[str] = None):
        """Initialize the project store.

        Args:
            projects_root: Root directory for all projects.
                          If None, uses settings.projects_root.
        """
        self.projects_root = Path(projects_root or settings.projects_root)
        self.projects_root.mkdir(parents=True, exist_ok=True)

    def create_project(self, project_id: str, name: str) -> Path:
        """Create a new project repository.

        Args:
            project_id: Unique project identifier
            name: Human-readable project name

        Returns:
            Path to the project directory
        """
        project_path = self.projects_root / project_id
        project_path.mkdir(parents=True, exist_ok=True)

        # Initialize Git repository
        repo = Repo.init(project_path)

        # Configure Git user
        config = repo.config_writer()
        config.set_value("user", "name", "SakuraAgentTeam")
        config.set_value("user", "email", "agent@sakura.local")
        config.release()

        # Create initial commit
        readme_path = project_path / "README.md"
        readme_path.write_text(f"# {name}\n\nGenerated by SakuraAgentTeam\n")

        repo.index.add(["README.md"])
        repo.index.commit("Initial commit: Project created")

        logger.info(
            "project_created",
            project_id=project_id,
            name=name,
            path=str(project_path),
        )

        return project_path

    def get_project(self, project_id: str) -> Optional[Repo]:
        """Get a project repository.

        Args:
            project_id: Project identifier

        Returns:
            Git repository or None if not found
        """
        project_path = self.projects_root / project_id
        if not project_path.exists():
            return None

        try:
            return Repo(project_path)
        except git.InvalidGitRepositoryError:
            return None

    def list_projects(self) -> List[dict]:
        """List all projects.

        Returns:
            List of project metadata
        """
        projects = []

        for project_dir in self.projects_root.iterdir():
            if project_dir.is_dir():
                try:
                    repo = Repo(project_dir)
                    projects.append({
                        "id": project_dir.name,
                        "path": str(project_dir),
                        "last_commit": repo.head.commit.message,
                        "last_commit_time": datetime.fromtimestamp(
                            repo.head.commit.committed_date
                        ).isoformat(),
                    })
                except git.InvalidGitRepositoryError:
                    continue

        return projects

    def add_file(
        self,
        project_id: str,
        file_path: str,
        content: str,
        commit_message: Optional[str] = None,
    ) -> bool:
        """Add or update a file in a project.

        Args:
            project_id: Project identifier
            file_path: Relative path within the project
            content: File content
            commit_message: Commit message (auto-generated if None)

        Returns:
            True if successful
        """
        repo = self.get_project(project_id)
        if not repo:
            logger.error("project_not_found", project_id=project_id)
            return False

        project_path = self.projects_root / project_id
        full_path = project_path / file_path

        # Create parent directories
        full_path.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        full_path.write_text(content)

        # Add to Git
        repo.index.add([file_path])

        # Commit
        if not commit_message:
            commit_message = f"Update {file_path}"

        repo.index.commit(commit_message)

        logger.info(
            "project_file_added",
            project_id=project_id,
            file_path=file_path,
            size=len(content),
        )

        return True

    def read_file(self, project_id: str, file_path: str) -> Optional[str]:
        """Read a file from a project.

        Args:
            project_id: Project identifier
            file_path: Relative path within the project

        Returns:
            File content or None if not found
        """
        project_path = self.projects_root / project_id
        full_path = project_path / file_path

        if not full_path.exists():
            return None

        return full_path.read_text()

    def list_files(self, project_id: str, directory: str = "") -> List[dict]:
        """List files in a project directory.

        Args:
            project_id: Project identifier
            directory: Relative directory path (root if empty)

        Returns:
            List of file metadata
        """
        project_path = self.projects_root / project_id
        target_path = project_path / directory if directory else project_path

        if not target_path.exists():
            return []

        files = []
        for item in target_path.iterdir():
            if item.name.startswith(".git"):
                continue

            relative_path = str(item.relative_to(project_path))
            files.append({
                "name": item.name,
                "path": relative_path,
                "type": "directory" if item.is_dir() else "file",
                "size": item.stat().st_size if item.is_file() else 0,
            })

        return files

    def create_branch(
        self, project_id: str, branch_name: str, from_branch: str = "main"
    ) -> bool:
        """Create a new branch.

        Args:
            project_id: Project identifier
            branch_name: New branch name
            from_branch: Source branch

        Returns:
            True if successful
        """
        repo = self.get_project(project_id)
        if not repo:
            return False

        try:
            repo.git.checkout(from_branch)
            repo.git.checkout("-b", branch_name)

            logger.info(
                "project_branch_created",
                project_id=project_id,
                branch_name=branch_name,
                from_branch=from_branch,
            )

            return True

        except git.GitCommandError as e:
            logger.error("project_branch_failed", error=str(e))
            return False

    def get_commit_history(self, project_id: str, limit: int = 10) -> List[dict]:
        """Get commit history for a project.

        Args:
            project_id: Project identifier
            limit: Maximum number of commits to return

        Returns:
            List of commit metadata
        """
        repo = self.get_project(project_id)
        if not repo:
            return []

        commits = []
        for commit in list(repo.iter_commits(max_count=limit)):
            commits.append({
                "hash": commit.hexsha[:8],
                "message": commit.message,
                "author": commit.author.name,
                "time": datetime.fromtimestamp(commit.committed_date).isoformat(),
            })

        return commits

    def rollback(self, project_id: str, commit_hash: str) -> bool:
        """Rollback to a specific commit.

        Args:
            project_id: Project identifier
            commit_hash: Commit hash to rollback to

        Returns:
            True if successful
        """
        repo = self.get_project(project_id)
        if not repo:
            return False

        try:
            repo.git.reset("--hard", commit_hash)

            logger.info(
                "project_rollback",
                project_id=project_id,
                commit_hash=commit_hash,
            )

            return True

        except git.GitCommandError as e:
            logger.error("project_rollback_failed", error=str(e))
            return False


# Global project store instance
project_store = ProjectStore()
