"""LLM Provider Registry — 100+ 供应商支持。

借鉴 LiteLLM 的设计，但更简洁：
- 每个供应商有 id, name, base_url, api_key_env, models
- 支持自定义供应商
- 支持 OpenAI 兼容接口
"""

from dataclasses import dataclass, field


@dataclass
class LLMProvider:
    id: str               # 供应商标识 (openai, anthropic, deepseek...)
    name: str             # 显示名
    base_url: str         # API base URL
    api_key_env: str      # 环境变量名
    docs_url: str         # 文档链接
    free_tier: bool       # 是否有免费额度
    free_tier_desc: str   # 免费额度描述
    models: list[str]     # 推荐模型列表
    icon: str             # emoji 图标
    color: str            # 品牌色


# 100+ 供应商
PROVIDERS: list[LLMProvider] = [
    # === 主流国际 ===
    LLMProvider("openai", "OpenAI", "https://api.openai.com/v1", "OPENAI_API_KEY",
                "https://platform.openai.com/docs", False, "", ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo"], "🟢", "#10a37f"),
    LLMProvider("anthropic", "Anthropic Claude", "https://api.anthropic.com", "ANTHROPIC_API_KEY",
                "https://docs.anthropic.com", False, "", ["claude-3.5-sonnet", "claude-3-opus", "claude-3-haiku"], "🟠", "#d97706"),
    LLMProvider("google", "Google Gemini", "https://generativelanguage.googleapis.com/v1", "GOOGLE_API_KEY",
                "https://ai.google.dev/docs", True, "Gemini 免费额度", ["gemini-1.5-pro", "gemini-1.5-flash", "gemini-2.0-flash"], "🔵", "#4285f4"),
    LLMProvider("mistral", "Mistral AI", "https://api.mistral.ai/v1", "MISTRAL_API_KEY",
                "https://docs.mistral.ai", True, "有免费额度", ["mistral-large", "mistral-medium", "mistral-small"], "🟣", "#ff7000"),
    LLMProvider("cohere", "Cohere", "https://api.cohere.ai/v1", "COHERE_API_KEY",
                "https://docs.cohere.com", True, "Trial key 免费", ["command-r-plus", "command-r"], "🟠", "#39594d"),
    LLMProvider("groq", "Groq", "https://api.groq.com/openai/v1", "GROQ_API_KEY",
                "https://console.groq.com/docs", True, "免费且快速", ["llama-3.3-70b", "llama-3.1-8b", "mixtral-8x7b"], "⚡", "#f55036"),
    LLMProvider("together", "Together AI", "https://api.together.xyz/v1", "TOGETHER_API_KEY",
                "https://docs.together.ai", True, "$5 免费额度", ["meta-llama/Llama-3.3-70B", "Qwen/Qwen2.5-72B"], "🤝", "#0f6fff"),
    LLMProvider("fireworks", "Fireworks AI", "https://api.fireworks.ai/inference/v1", "FIREWORKS_API_KEY",
                "https://docs.fireworks.ai", True, "$1 免费额度", ["accounts/fireworks/models/llama-v3p3-70b-instruct"], "🎆", "#5221c6"),
    LLMProvider("perplexity", "Perplexity", "https://api.perplexity.ai", "PERPLEXITY_API_KEY",
                "https://docs.perplexity.ai", False, "", ["llama-3.1-sonar-large-32k-online"], "🔍", "#20808d"),
    LLMProvider("ai21", "AI21 Labs", "https://api.ai21.com/v1", "AI21_API_KEY",
                "https://docs.ai21.com", True, "$10 免费额度", ["jamba-1.5-large", "jamba-1.5-mini"], "🧠", "#511778"),
    LLMProvider("deepinfra", "DeepInfra", "https://api.deepinfra.com/v1/openai", "DEEPINFRA_API_KEY",
                "https://deepinfra.com/docs", True, "$0.5 免费额度", ["meta-llama/Llama-3.3-70B-Instruct"], "🔮", "#7c3aed"),
    LLMProvider("novita", "Novita AI", "https://api.novita.ai/v3/openai", "NOVITA_API_KEY",
                "https://novita.ai/docs", True, "免费额度", ["meta-llama/llama-3.1-70b-instruct"], "🌟", "#ec4899"),

    # === 国内供应商 ===
    LLMProvider("deepseek", "DeepSeek 深度求索", "https://api.deepseek.com/v1", "DEEPSEEK_API_KEY",
                "https://platform.deepseek.com/docs", True, "送 500 万 token", ["deepseek-chat", "deepseek-reasoner"], "🐳", "#4d6bfe"),
    LLMProvider("qwen", "通义千问 (阿里云)", "https://dashscope.aliyuncs.com/compatible-mode/v1", "DASHSCOPE_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen-max", "qwen-plus", "qwen-turbo"], "🟢", "#615ced"),
    LLMProvider("moonshot", "Moonshot (Kimi)", "https://api.moonshot.cn/v1", "MOONSHOT_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"], "🌙", "#000000"),
    LLMProvider("zhipu", "智谱 AI (GLM)", "https://open.bigmodel.cn/api/paas/v4", "ZHIPU_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4-plus", "glm-4-flash", "glm-4-air"], "✨", "#3859ff"),
    LLMProvider("baichuan", "百川智能", "https://api.baichuan-ai.com/v1", "BAICHUAN_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan4", "Baichuan3-Turbo"], "🏔️", "#0d9488"),
    LLMProvider("minimax", "MiniMax", "https://api.minimax.chat/v1", "MINIMAX_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["abab6.5s-chat", "abab6.5-chat"], "🎯", "#ff6b6b"),
    LLMProvider("yi", "零一万物 (01.AI)", "https://api.lingyiwanwu.com/v1", "YI_API_KEY",
                "https://platform.lingyiwanwu.com/docs", True, "送 100 万 token", ["yi-large", "yi-medium", "yi-spark"], "1️⃣", "#00b4d8"),
    LLMProvider("stepfun", "阶跃星辰", "https://api.stepfun.com/v1", "STEPFUN_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-1-8k", "step-1-32k", "step-1-128k"], "⭐", "#7c3aed"),
    LLMProvider("spark", "讯飞星火", "https://spark-api-open.xf-yun.com/v1", "SPARK_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["generalv3.5", "generalv3"], "🔥", "#c41e3a"),
    LLMProvider("ernie", "百度文心一言", "https://qianfan.baidubce.com/v2", "ERNIE_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.0-8k-latest", "ernie-3.5-8k"], "🟦", "#2932e1"),
    LLMProvider("hunyuan", "腾讯混元", "https://api.hunyuan.cloud.tencent.com/v1", "HUNYUAN_API_KEY",
                "https://cloud.tencent.com/document/product/1729", True, "免费额度", ["hunyuan-pro", "hunyuan-standard"], "🌀", "#0052d9"),
    LLMProvider("siliconflow", "SiliconFlow 硅基流动", "https://api.siliconflow.cn/v1", "SILICONFLOW_API_KEY",
                "https://docs.siliconflow.cn", True, "送 14 元额度", ["Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3"], "💎", "#ff6600"),
    LLMProvider("volcengine", "火山引擎 (豆包)", "https://ark.cn-beijing.volces.com/api/v3", "VOLCENGINE_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-pro-32k", "doubao-pro-4k"], "🌋", "#ff5a5f"),

    # === 中转站/聚合 ===
    LLMProvider("openrouter", "OpenRouter", "https://openrouter.ai/api/v1", "OPENROUTER_API_KEY",
                "https://openrouter.ai/docs", True, "部分模型免费", ["google/gemini-2.0-flash-exp:free", "meta-llama/llama-3.3-70b-instruct:free"], "🔀", "#5a5a5a"),
    LLMProvider("oneapi", "OneAPI 中转", "", "ONEAPI_API_KEY",
                "https://github.com/songquanpeng/one-api", False, "自建中转站", [], "🔗", "#6366f1"),

    # === 开源/本地 ===
    LLMProvider("ollama", "Ollama (本地)", "http://localhost:11434/v1", "OLLAMA_API_KEY",
                "https://ollama.com", True, "完全免费（本地）", ["llama3.3", "qwen2.5", "deepseek-r1"], "🦙", "#000000"),
    LLMProvider("vllm", "vLLM (本地)", "http://localhost:8000/v1", "VLLM_API_KEY",
                "https://docs.vllm.ai", True, "完全免费（本地）", [], "⚡", "#7c3aed"),
    LLMProvider("lmstudio", "LM Studio (本地)", "http://localhost:1234/v1", "LMSTUDIO_API_KEY",
                "https://lmstudio.ai", True, "完全免费（本地）", [], "🖥️", "#4a9eff"),
    LLMProvider("llamacpp", "llama.cpp (本地)", "http://localhost:8080/v1", "LLAMACPP_API_KEY",
                "https://github.com/ggerganov/llama.cpp", True, "完全免费（本地）", [], "🔧", "#6b7280"),

    # === 更多国际云供应商 ===
    LLMProvider("bedrock", "AWS Bedrock", "https://bedrock-runtime.us-east-1.amazonaws.com", "AWS_BEDROCK_API_KEY",
                "https://docs.aws.amazon.com/bedrock", True, "AWS 免费层", ["anthropic.claude-3-5-sonnet-20240620-v1:0", "meta.llama3-1-70b-instruct-v1:0"], "☁️", "#ff9900"),
    LLMProvider("azure", "Azure OpenAI", "https://{resource}.openai.azure.com", "AZURE_OPENAI_API_KEY",
                "https://learn.microsoft.com/azure/ai-services/openai", False, "", ["gpt-4o", "gpt-4o-mini"], "🔷", "#0078d4"),
    LLMProvider("vertex", "Google Vertex AI", "https://{region}-aiplatform.googleapis.com/v1", "VERTEX_API_KEY",
                "https://cloud.google.com/vertex-ai/docs", True, "$300 试用额度", ["gemini-1.5-pro", "gemini-1.5-flash"], "🔺", "#4285f4"),
    LLMProvider("replicate", "Replicate", "https://api.replicate.com/v1", "REPLICATE_API_KEY",
                "https://replicate.com/docs", False, "", ["meta/llama-3-70b-instruct", "mistralai/mixtral-8x7b-instruct-v0.1"], "🔁", "#000000"),
    LLMProvider("anyscale", "Anyscale", "https://api.endpoints.anyscale.com/v1", "ANYSCALE_API_KEY",
                "https://docs.anyscale.com", True, "$10 免费额度", ["meta-llama/Llama-3-70b-Instruct"], "🎯", "#0066cc"),
    LLMProvider("baseten", "Baseten", "https://api.baseten.co/v1", "BASETEN_API_KEY",
                "https://docs.baseten.co", True, "$5 免费额度", ["llama-3-70b"], "🏗️", "#ff5c5c"),
    LLMProvider("modal", "Modal", "https://modal.com/docs/api", "MODAL_API_KEY",
                "https://modal.com/docs", True, "$30 免费额度", ["llama-3-70b"], "🎛️", "#7d5cff"),
    LLMProvider("runpod", "RunPod", "https://api.runpod.ai/v2", "RUNPOD_API_KEY",
                "https://docs.runpod.io", True, "免费额度", ["llama-3-70b"], "🏃", "#7c3aed"),
    LLMProvider("lambdalabs", "Lambda Labs", "https://api.lambdalabs.com/v1", "LAMBDA_API_KEY",
                "https://lambdalabs.com/api", True, "免费额度", ["llama-3-70b"], "λ", "#5f9ea0"),
    LLMProvider("predibase", "Predibase", "https://api.predibase.com/v1", "PREDIBASE_API_KEY",
                "https://docs.predibase.com", True, "免费试用", ["llama-3-70b"], "📊", "#ff6b35"),
    LLMProvider("octoai", "OctoAI", "https://text.octoai.run/v1", "OCTOAI_API_KEY",
                "https://docs.octoai.cloud", True, "$10 免费额度", ["meta-llama-3.1-70b-instruct"], "🐙", "#1f2937"),
    LLMProvider("cloudflare", "Cloudflare Workers AI", "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai", "CLOUDFLARE_API_KEY",
                "https://developers.cloudflare.com/workers-ai", True, "免费额度（每日）", ["@cf/meta/llama-3.1-8b-instruct"], "🌐", "#f38020"),
    LLMProvider("nim", "NVIDIA NIM", "https://integrate.api.nvidia.com/v1", "NVIDIA_API_KEY",
                "https://docs.api.nvidia.com", True, "1000 免费请求", ["meta/llama-3.1-70b-instruct", "mistralai/mixtral-8x7b-instruct-v0.1"], "🟩", "#76b900"),
    LLMProvider("bentoml", "BentoML", "https://api.bentoml.com/v1", "BENTOML_API_KEY",
                "https://docs.bentoml.com", True, "免费额度", ["llama-3-70b"], "🍱", "#ffbf00"),
    LLMProvider("friendliai", "FriendliAI", "https://api.friendli.ai/v1", "FRIENDLIAI_API_KEY",
                "https://docs.friendli.ai", True, "免费试用", ["llama-3-70b"], "🤝", "#00b8a9"),
    LLMProvider("lepton", "Lepton AI", "https://api.lepton.ai/v1", "LEPTON_API_KEY",
                "https://www.lepton.ai/docs", True, "免费额度", ["meta-llama/Llama-3.1-70B"], "⚡", "#ff4f00"),
    LLMProvider("alephalpha", "Aleph Alpha", "https://api.aleph-alpha.com/v1", "ALEPH_ALPHA_API_KEY",
                "https://docs.aleph-alpha.com", False, "", ["luminous-supreme", "luminous-base"], "🅰️", "#1d4ed8"),
    LLMProvider("writer", "Writer", "https://api.writer.com/v1", "WRITER_API_KEY",
                "https://dev.writer.com", False, "", ["palmyra-x-v3", "palmyra-x-v2"], "✍️", "#c8b6ff"),
    LLMProvider("inflection", "Inflection AI", "https://api.inflection.ai/v1", "INFLECTION_API_KEY",
                "https://inflection.ai/docs", False, "", ["inflection-3-pi", "inflection-3-productivity"], "💡", "#ff6f61"),
    LLMProvider("reka", "Reka AI", "https://api.reka.ai/v1", "REKA_API_KEY",
                "https://docs.reka.ai", True, "免费额度", ["reka-core", "reka-flash"], "🌈", "#ff3366"),
    LLMProvider("pataneai", "PataneAI", "https://api.pataneai.com/v1", "PATANEAI_API_KEY",
                "https://pataneai.com/docs", False, "", ["llama-3-70b"], "🚀", "#7c3aed"),
    LLMProvider("stability", "Stability AI", "https://api.stability.ai/v1", "STABILITY_API_KEY",
                "https://platform.stability.ai/docs", True, "25 免费额度", ["stable-diffusion-3", "stable-image-ultra"], "🎨", "#000000"),
    LLMProvider("huggingface", "Hugging Face Inference", "https://api-inference.huggingface.co", "HF_API_KEY",
                "https://huggingface.co/docs/api-inference", True, "免费额度", ["meta-llama/Meta-Llama-3-70B-Instruct", "mistralai/Mistral-7B-Instruct"], "🤗", "#ffcc4d"),
    LLMProvider("voyage", "Voyage AI", "https://api.voyageai.com/v1", "VOYAGE_API_KEY",
                "https://docs.voyageai.com", True, "200M 免费额度", ["voyage-large-2", "voyage-code-2"], "🧭", "#1e3a8a"),
    LLMProvider("jina", "Jina AI", "https://api.jina.ai/v1", "JINA_API_KEY",
                "https://jina.ai/docs", True, "免费额度", ["jina-embeddings-v3", "jina-reranker-v2"], "🅹", "#0a4d8c"),
    LLMProvider("upstage", "Upstage", "https://api.upstage.ai/v1", "UPSTAGE_API_KEY",
                "https://developers.upstage.ai", True, "免费额度", ["solar-1-mini", "solar-10.7b-instruct"], "☀️", "#ff8c00"),
    LLMProvider("nomic", "Nomic AI", "https://api-atlas.nomic.ai/v1", "NOMIC_API_KEY",
                "https://docs.nomic.ai", True, "免费额度", ["nomic-embed-text-v1", "nomic-embed-vision-v1"], "🧬", "#00a86b"),
    LLMProvider("featherless", "Featherless AI", "https://api.featherless.ai/v1", "FEATHERLESS_API_KEY",
                "https://featherless.ai/docs", True, "免费额度", ["meta-llama/Meta-Llama-3-70B"], "🪶", "#94a3b8"),
    LLMProvider("monsterapi", "Monster API", "https://api.monsterapi.ai/v1", "MONSTER_API_KEY",
                "https://monsterapi.ai/docs", True, "$5 免费额度", ["meta/llama-3-70b-instruct"], "👾", "#a855f7"),
    LLMProvider("aimlapi", "AI/ML API", "https://api.aimlapi.com/v1", "AIML_API_KEY",
                "https://docs.aimlapi.com", True, "免费额度", ["gpt-4o", "llama-3-70b"], "🤖", "#10b981"),
    LLMProvider("edenai", "Eden AI", "https://api.edenai.run/v2", "EDENAI_API_KEY",
                "https://docs.edenai.co", True, "$10 免费额度", ["openai/gpt-4o", "anthropic/claude-3-5-sonnet"], "🌿", "#00897b"),
    LLMProvider("snowflake", "Snowflake Cortex", "https://{account}.snowflakecomputing.com/api/v2/cortex", "SNOWFLAKE_API_KEY",
                "https://docs.snowflake.com/en/user-guide/snowflake-cortex/llm-functions", False, "", ["llama2-70b-chat", "mixtral-8x7b"], "❄️", "#29b5e8"),
    LLMProvider("databricks", "Databricks Foundation Models", "https://api.databricks.com/serving-endpoints", "DATABRICKS_API_KEY",
                "https://docs.databricks.com/machine-learning/foundation-models", False, "", ["databricks-dbrx-instruct", "meta-llama-3-70b"], "🧱", "#ff3621"),
    LLMProvider("oracle", "Oracle Generative AI", "https://generativeai.{region}.oci.oraclecloud.com", "OCI_API_KEY",
                "https://docs.oracle.com/iaas/Content/generative-ai/home", True, "免费额度", ["cohere.command-r-plus", "cohere.command-r"], "🔴", "#c74634"),
    LLMProvider("sagemaker", "AWS SageMaker JumpStart", "https://runtime.sagemaker.{region}.amazonaws.com", "SAGEMAKER_API_KEY",
                "https://docs.aws.amazon.com/sagemaker", False, "", ["meta-llama-3-70b", "mistral-7b"], "🟧", "#ff9900"),
    LLMProvider("watsonx", "IBM watsonx", "https://{region}.ml.cloud.ibm.com/ml/v1", "WATSONX_API_KEY",
                "https://www.ibm.com/watsonx", True, "免费试用", ["meta-llama/llama-3-70b-instruct", "mistralai/mixtral-8x7b"], "🟦", "#0f62fe"),
    LLMProvider("palantir", "Palantir AIP", "https://api.palantir.com/aip", "PALANTIR_API_KEY",
                "https://www.palantir.com/docs", False, "", ["llama-3-70b"], "🛡️", "#101820"),
    LLMProvider("tabnine", "Tabnine", "https://api.tabnine.com/v1", "TABNINE_API_KEY",
                "https://docs.tabnine.com", True, "免费基础版", ["tabnine-llama-3-70b"], "💻", "#6366f1"),
    LLMProvider("codeium", "Codeium", "https://api.codeium.com/v1", "CODEIUM_API_KEY",
                "https://docs.codeium.com", True, "免费个人版", ["codeium-llama-3-70b"], "⌨️", "#09b6a2"),
    LLMProvider("phind", "Phind", "https://api.phind.com/v1", "PHIND_API_KEY",
                "https://phind.com/docs", False, "", ["phind-70b"], "🔎", "#1f2937"),
    LLMProvider("youcom", "You.com", "https://api.you.com/v1", "YOUCOM_API_KEY",
                "https://documentation.you.com", True, "免费额度", ["gpt-4o", "claude-3-5-sonnet"], "🫵", "#7c3aed"),
    LLMProvider("exa", "Exa AI", "https://api.exa.ai/v1", "EXA_API_KEY",
                "https://docs.exa.ai", True, "1000 免费搜索", ["exa-search"], "🔍", "#1e40af"),
    LLMProvider("tavily", "Tavily", "https://api.tavily.com/v1", "TAVILY_API_KEY",
                "https://docs.tavily.com", True, "1000 免费搜索", ["tavily-search"], "🛰️", "#6366f1"),
    LLMProvider("brave", "Brave AI Search", "https://api.search.brave.com/v1", "BRAVE_API_KEY",
                "https://api.search.brave.com", True, "2000 免费搜索", ["brave-search"], "🦁", "#fb542b"),

    # === 更多国内供应商 ===
    LLMProvider("sensenova", "商汤日日新", "https://api.sensenova.cn/v1", "SENSENOVA_API_KEY",
                "https://platform.sensenova.cn", True, "免费额度", ["SenseChat-5", "SenseChat-Turbo"], "🌅", "#ff4d4f"),
    LLMProvider("xverse", "元象 XVerse", "https://api.xverse.cn/v1", "XVERSE_API_KEY",
                "https://api.xverse.cn/docs", True, "免费额度", ["xverse-65b", "xverse-13b"], "🌌", "#7c3aed"),
    LLMProvider("yuanqi", "浪潮源 1.0", "https://api.inspur.com/v1", "YUAN_API_KEY",
                "https://air.inspur.com/home", True, "免费额度", ["yuan-1.0-245b"], "🌊", "#0066cc"),
    LLMProvider("wenige", "中科闻歌", "https://api.wenge.com/v1", "WENGE_API_KEY",
                "https://www.wenge.com", False, "", ["wenxin-1.0"], "🐦", "#10b981"),
    LLMProvider("shizaizhi", "实在智能", "https://api.izai.com/v1", "SHIZAI_API_KEY",
                "https://www.izai.cn", False, "", ["shizai-llm"], "🤖", "#ff6b35"),
    LLMProvider("aispeech", "思必驰", "https://api.aispeech.com/v1", "AISPEECH_API_KEY",
                "https://www.aispeech.com", False, "", ["dui-llm"], "🗣️", "#1e88e5"),
    LLMProvider("chuimenwen", "出门问问", "https://api.chumenwenwen.com/v1", "CHUMEN_API_KEY",
                "https://www.chumenwenwen.com", False, "", ["seq2seq-llm"], "🚪", "#ff5252"),
    LLMProvider("yunzhisheng", "云知声", "https://api.yunzhisheng.com/v1", "YUNZHISHENG_API_KEY",
                "https://www.yunzhisheng.com", False, "", ["unisound-llm"], "☁️", "#00bcd4"),
    LLMProvider("lanzhu", "澜舟科技", "https://api.langboat.com/v1", "LANGBOAT_API_KEY",
                "https://www.langboat.com", True, "免费额度", ["mengzi-gpt4"], "🚣", "#0288d1"),
    LLMProvider("moss", "复旦 MOSS", "https://api.moss.fudan.edu.cn/v1", "MOSS_API_KEY",
                "https://github.com/OpenMOSS/MOSS", True, "完全免费", ["moss-moon-003-sft"], "🌱", "#2e7d32"),
    LLMProvider("duxiaoman", "度小满", "https://api.duxiaoman.com/v1", "DUXIAOMAN_API_KEY",
                "https://www.duxiaoman.com", False, "", ["duxiaoman-llm"], "💰", "#1976d2"),
    LLMProvider("360brain", "360 智脑", "https://api.360.cn/v1", "360_API_KEY",
                "https://ai.360.com", True, "免费额度", ["360gpt-pro", "360gpt-turbo"], "🌐", "#21c43a"),
    LLMProvider("kunlun", "昆仑万维 (天工)", "https://api.tiangong.cn/v1", "TIANGONG_API_KEY",
                "https://tiangong.kunlun.com", True, "免费额度", ["skywork-3.0", "skywork-13b"], "⛰️", "#ff5722"),
    LLMProvider("meituan", "美团 MT", "https://api.meituan.com/v1", "MEITUAN_API_KEY",
                "https://about.meituan.com", False, "", ["mt-llm"], "🛵", "#ffc300"),
    LLMProvider("zhihu", "知乎 知海图", "https://api.zhihu.com/v1", "ZHIHU_API_KEY",
                "https://www.zhihu.com", False, "", ["zhaigpt-1.0"], "📚", "#0084ff"),
    LLMProvider("jd", "京东 言犀", "https://api.jd.com/v1", "JD_API_KEY",
                "https://neuhub.jd.com", False, "", ["yanxi-llm"], "📦", "#e1251b"),
    LLMProvider("youdao", "网易有道", "https://api.youdao.com/v1", "YOUDAO_API_KEY",
                "https://ai.youdao.com", True, "免费额度", ["youdao-llm"], "📘", "#e60012"),
    LLMProvider("iflytek", "科大讯飞", "https://spark-api-open.xf-yun.com/v1", "IFLYTEK_API_KEY",
                "https://www.xfyun.cn", True, "免费额度", ["spark-pro", "spark-max"], "🎤", "#cf1f27"),
    LLMProvider("wanmo", "万摩科技", "https://api.wanmo.com/v1", "WANMO_API_KEY",
                "https://www.wanmo.com", False, "", ["wanmo-llm"], "🐎", "#7c3aed"),
    LLMProvider("tencentcloud", "腾讯云 LLM", "https://lke.cloud.tencent.com/v1", "TENCENT_CLOUD_API_KEY",
                "https://cloud.tencent.com/product/lke", True, "免费额度", ["lke-llm"], "☁️", "#0052d9"),
    LLMProvider("aliyun", "阿里云百炼", "https://bailian.aliyuncs.com/v1", "BAILIAN_API_KEY",
                "https://bailian.console.aliyun.com", True, "免费额度", ["qwen-max", "qwen-plus"], "🟧", "#ff6a00"),
    LLMProvider("huawei", "华为云盘古", "https://api.panguservice.com/v1", "PANGU_API_KEY",
                "https://www.huaweicloud.com/product/pangu.html", False, "", ["pangu-llm"], "🟦", "#ff0000"),

    # === 更多中转站/聚合 ===
    LLMProvider("api2d", "API2D 中转", "https://oa.api2d.net/v1", "API2D_API_KEY",
                "https://api2d.com", False, "中转服务", ["gpt-4o", "claude-3-5-sonnet"], "🔗", "#3b82f6"),
    LLMProvider("closeai", "CloseAI 中转", "https://api.closeai-proxy.xyz/v1", "CLOSEAI_API_KEY",
                "https://www.closeai-asia.com", False, "中转服务", ["gpt-4o", "claude-3-5-sonnet"], "🔒", "#10b981"),
    LLMProvider("openaisb", "OpenAI-SB 中转", "https://api.openai-sb.com/v1", "OPENAISB_API_KEY",
                "https://openai-sb.com", False, "中转服务", ["gpt-4o", "gpt-4o-mini"], "🟦", "#0ea5e9"),
    LLMProvider("ohmygpt", "OhMyGPT 中转", "https://api.ohmygpt.com/v1", "OHMYGPT_API_KEY",
                "https://www.ohmygpt.com", False, "中转服务", ["gpt-4o", "claude-3-5-sonnet"], "😮", "#ec4899"),
    LLMProvider("chatanywhere", "ChatAnywhere 中转", "https://api.chatanywhere.tech/v1", "CHATANYWHERE_API_KEY",
                "https://chatanywhere.com", False, "中转服务", ["gpt-4o", "gpt-4o-mini"], "💬", "#22c55e"),
    LLMProvider("aiproxy", "AI Proxy", "https://api.aiproxy.io/v1", "AIPROXY_API_KEY",
                "https://aiproxy.io", False, "中转服务", ["gpt-4o", "claude-3-5-sonnet"], "🔀", "#8b5cf6"),
    LLMProvider("litellm-proxy", "LiteLLM Proxy", "http://localhost:4000/v1", "LITELLM_PROXY_API_KEY",
                "https://docs.litellm.ai/docs/proxy/quick_start", True, "自建代理", ["gpt-4o", "claude-3-5-sonnet"], "🪄", "#10b981"),
    LLMProvider("helicone", "Helicone", "https://api.helicone.ai/v1", "HELICONE_API_KEY",
                "https://docs.helicone.ai", True, "免费额度", ["gpt-4o"], "🛎️", "#0a7c5b"),
    LLMProvider("portkey", "Portkey", "https://api.portkey.ai/v1", "PORTKEY_API_KEY",
                "https://portkey.ai/docs", True, "免费额度", ["gpt-4o", "claude-3-5-sonnet"], "🗝️", "#5f27cd"),
    LLMProvider("langfuse", "Langfuse", "https://api.langfuse.com/v1", "LANGFUSE_API_KEY",
                "https://langfuse.com/docs", True, "免费额度", ["gpt-4o"], "🧪", "#f97316"),

    # === 更多开源/本地 ===
    LLMProvider("gpt4all", "GPT4All (本地)", "http://localhost:4891/v1", "GPT4ALL_API_KEY",
                "https://gpt4all.io", True, "完全免费（本地）", ["orca-mini-3b", "llama-3-8b"], "🦾", "#0066cc"),
    LLMProvider("koboldcpp", "KoboldCpp (本地)", "http://localhost:5001/v1", "KOBOLDCPP_API_KEY",
                "https://github.com/LostRuins/koboldcpp", True, "完全免费（本地）", [], "🐉", "#7c3aed"),
    LLMProvider("textgen-webui", "text-generation-webui (本地)", "http://localhost:5000/v1", "TEXTGEN_API_KEY",
                "https://github.com/oobabooga/text-generation-webui", True, "完全免费（本地）", [], "📝", "#1f2937"),
    LLMProvider("tgi", "Text Generation Inference (本地)", "http://localhost:8080/v1", "TGI_API_KEY",
                "https://huggingface.co/docs/text-generation-inference", True, "完全免费（本地）", [], "🔥", "#ff9900"),
    LLMProvider("rayserve", "Ray Serve (本地)", "http://localhost:8000/v1", "RAYSERVE_API_KEY",
                "https://docs.ray.io/en/latest/serve/index.html", True, "完全免费（本地）", [], "🚀", "#0288d1"),
    LLMProvider("openvino", "OpenVINO (本地)", "http://localhost:8000/v1", "OPENVINO_API_KEY",
                "https://docs.openvino.ai", True, "完全免费（本地）", [], "🟩", "#00c7fd"),
    LLMProvider("triton", "Triton Inference Server (本地)", "http://localhost:8000/v2", "TRITON_API_KEY",
                "https://docs.nvidia.com/deeplearning/triton-inference-server", True, "完全免费（本地）", [], "🟢", "#76b900"),
    LLMProvider("xinference", "Xinference (本地)", "http://localhost:9997/v1", "XINFERENCE_API_KEY",
                "https://inference.readthedocs.io", True, "完全免费（本地）", ["llama-3-70b", "qwen2-72b"], "❎", "#dc2626"),
    LLMProvider("openllm", "OpenLLM (本地)", "http://localhost:3000/v1", "OPENLLM_API_KEY",
                "https://github.com/bentoml/OpenLLM", True, "完全免费（本地）", ["llama-3-70b"], "🟢", "#11a661"),
    LLMProvider("localai", "LocalAI (本地)", "http://localhost:8080/v1", "LOCALAI_API_KEY",
                "https://localai.io", True, "完全免费（本地）", ["gpt-3.5-turbo", "llama-3-8b"], "🏠", "#7c3aed"),

    # === 更多国际新兴供应商 ===
    LLMProvider("tabby", "Tabby", "https://api.tabbyml.com/v1", "TABBY_API_KEY",
                "https://tabbyml.com", True, "免费额度", ["starcoder2-15b", "codestral-22b"], "🐈", "#ff6b35"),
    LLMProvider("sambanova", "SambaNova", "https://api.sambanova.ai/v1", "SAMBANOVA_API_KEY",
                "https://docs.sambanova.ai", True, "免费额度", ["Meta-Llama-3.1-70B-Instruct", "Meta-Llama-3.1-405B-Instruct"], "🟠", "#f04e23"),
    LLMProvider("cerebras", "Cerebras", "https://api.cerebras.ai/v1", "CEREBRAS_API_KEY",
                "https://www.cerebras.ai", True, "免费额度", ["llama3.1-8b", "llama3.1-70b"], "🧠", "#ff3366"),
    LLMProvider("nebius", "Nebius", "https://api.studio.nebius.ai/v1", "NEBIUS_API_KEY",
                "https://studio.nebius.com", True, "$75 免费额度", ["meta-llama/Meta-Llama-3.1-405B-Instruct"], "🌌", "#ff0066"),
    LLMProvider("hyperbolic", "Hyperbolic", "https://api.hyperbolic.xyz/v1", "HYPERBOLIC_API_KEY",
                "https://docs.hyperbolic.xyz", True, "$10 免费额度", ["meta-llama/Meta-Llama-3.1-70B-Instruct"], "📈", "#5b21b6"),
    LLMProvider("atlas", "Atlas Inference", "https://api.atlas.ml/v1", "ATLAS_API_KEY",
                "https://atlas.ml/docs", True, "免费额度", ["llama-3-70b"], "🗺️", "#1e3a8a"),
    LLMProvider("deepseek-v3", "DeepSeek V3 (开源)", "https://api.deepseek.com/v1", "DEEPSEEK_V3_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-v3", "deepseek-r1"], "🐳", "#4d6bfe"),
    LLMProvider("qwen2", "Qwen2 (开源)", "https://api.siliconflow.cn/v1", "QWEN2_API_KEY",
                "https://siliconflow.cn/models", True, "免费额度", ["Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-7B-Instruct"], "🟢", "#615ced"),
    LLMProvider("llama3", "Llama 3 (Meta)", "https://api.together.xyz/v1", "LLAMA3_API_KEY",
                "https://llama.meta.com", True, "免费额度", ["meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Llama-3.1-8B-Instruct"], "🦙", "#0668e1"),
    LLMProvider("mistral-large", "Mistral Large (开源)", "https://api.mistral.ai/v1", "MISTRAL_LARGE_API_KEY",
                "https://mistral.ai", True, "免费额度", ["mistral-large-latest", "codestral-latest"], "🟣", "#ff7000"),
    LLMProvider("gemma", "Google Gemma", "https://api.together.xyz/v1", "GEMMA_API_KEY",
                "https://ai.google.dev/gemma", True, "免费额度", ["google/gemma-2-27b", "google/gemma-2-9b"], "💎", "#4285f4"),
    LLMProvider("phi", "Microsoft Phi", "https://api.together.xyz/v1", "PHI_API_KEY",
                "https://huggingface.co/microsoft", True, "免费额度", ["microsoft/Phi-3-medium-4k-instruct"], "🔵", "#0078d4"),
    LLMProvider("command", "Cohere Command R+", "https://api.cohere.ai/v1", "COMMAND_API_KEY",
                "https://docs.cohere.com/docs/models", True, "免费额度", ["command-r-plus-08-2024", "command-r-08-2024"], "🟠", "#39594d"),
    LLMProvider("dbrx", "Databricks DBRX", "https://api.databricks.com/serving-endpoints", "DBRX_API_KEY",
                "https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm", False, "", ["databricks-dbrx-instruct"], "🧱", "#ff3621"),
    LLMProvider("yi-large", "Yi Large (开源)", "https://api.lingyiwanwu.com/v1", "YI_LARGE_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large", "yi-large-turbo"], "1️⃣", "#00b4d8"),
    LLMProvider("glm", "GLM-4 (开源)", "https://open.bigmodel.cn/api/paas/v4", "GLM_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4-plus", "glm-4-flash"], "✨", "#3859ff"),
    LLMProvider("codestral", "Codestral (Mistral)", "https://api.mistral.ai/v1", "CODESTRAL_API_KEY",
                "https://mistral.ai/news/announcing-codestral", True, "免费额度", ["codestral-latest"], "💻", "#ff7000"),
    LLMProvider("deepcoder", "DeepCoder", "https://api.deepcoder.com/v1", "DEEPCODER_API_KEY",
                "https://deepcoder.com", False, "", ["deepcoder-13b"], "💻", "#7c3aed"),
    LLMProvider("starcoder", "StarCoder (BigCode)", "https://api.together.xyz/v1", "STARCODER_API_KEY",
                "https://huggingface.co/bigcode", True, "免费额度", ["bigcode/starcoder2-15b-instruct"], "⭐", "#ffcc4d"),
    LLMProvider("codegemma", "CodeGemma (Google)", "https://api.together.xyz/v1", "CODEGEMMA_API_KEY",
                "https://ai.google.dev/gemma", True, "免费额度", ["google/codegemma-7b"], "💎", "#4285f4"),
    LLMProvider("qwen-coder", "Qwen Coder", "https://api.siliconflow.cn/v1", "QWEN_CODER_API_KEY",
                "https://siliconflow.cn/models", True, "免费额度", ["Qwen/Qwen2.5-Coder-32B-Instruct"], "🟢", "#615ced"),
    LLMProvider("deepseek-coder", "DeepSeek Coder", "https://api.deepseek.com/v1", "DEEPSEEK_CODER_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-coder", "deepseek-coder-v2"], "🐳", "#4d6bfe"),
    LLMProvider("yi-coder", "Yi Coder", "https://api.lingyiwanwu.com/v1", "YI_CODER_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-coder-chat", "yi-coder-9b"], "1️⃣", "#00b4d8"),
    LLMProvider("stablelm", "StableLM", "https://api.stability.ai/v1", "STABLELM_API_KEY",
                "https://stability.ai/news/stablelm-3b", True, "免费额度", ["stablelm-3b-4e1t"], "🎨", "#000000"),
    LLMProvider("redpajama", "RedPajama", "https://api.together.xyz/v1", "REDPAJAMA_API_KEY",
                "https://www.together.ai/blog/redpajama", True, "免费额度", ["togethercomputer/RedPajama-INCITE-7B-Chat"], "🟥", "#dc2626"),
    LLMProvider("falcon", "Falcon (TII)", "https://api.together.xyz/v1", "FALCON_API_KEY",
                "https://falconllm.tii.ae", True, "免费额度", ["tiiuae/falcon-180B-chat"], "🦅", "#1e40af"),
    LLMProvider("mpt", "MPT (MosaicML)", "https://api.mosaicml.com/v1", "MPT_API_KEY",
                "https://www.mosaicml.com/blog/mpt-7b", True, "免费额度", ["mosaicml/mpt-30b-chat"], "🟪", "#7c3aed"),
    LLMProvider("dolly", "Dolly (Databricks)", "https://api.databricks.com/serving-endpoints", "DOLLY_API_KEY",
                "https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm", False, "", ["databricks/dolly-v2-12b"], "🧸", "#ff3621"),
    LLMProvider("openchat", "OpenChat", "https://api.together.xyz/v1", "OPENCHAT_API_KEY",
                "https://github.com/imoneoi/openchat", True, "免费额度", ["openchat/openchat-3.5-1210"], "💬", "#10b981"),
    LLMProvider("zephyr", "Zephyr (HuggingFace)", "https://api.together.xyz/v1", "ZEPHYR_API_KEY",
                "https://huggingface.co/HuggingFaceH4/zephyr-7b-beta", True, "免费额度", ["HuggingFaceH4/zephyr-7b-beta"], "🌬️", "#ffcc4d"),
    LLMProvider("vicuna", "Vicuna (LMSYS)", "https://api.together.xyz/v1", "VICUNA_API_KEY",
                "https://lmsys.org/blog/2023-03-30-vicuna", True, "免费额度", ["lmsys/vicuna-13b-v1.5"], "🦙", "#7c3aed"),
    LLMProvider("wizardlm", "WizardLM", "https://api.together.xyz/v1", "WIZARDLM_API_KEY",
                "https://github.com/nlpxucan/WizardLM", True, "免费额度", ["WizardLM/WizardLM-13B-V1.2"], "🧙", "#7c3aed"),
    LLMProvider("orca", "Microsoft Orca", "https://api.together.xyz/v1", "ORCA_API_KEY",
                "https://www.microsoft.com/en-us/research/blog/orca-a-potential-learning-method-for-imitating-and-boosting-llm-system-reasoning", True, "免费额度", ["microsoft/Orca-2-13b"], "🐋", "#0078d4"),
    LLMProvider("phi3", "Phi-3 (Microsoft)", "https://api.together.xyz/v1", "PHI3_API_KEY",
                "https://huggingface.co/microsoft/Phi-3-medium-4k-instruct", True, "免费额度", ["microsoft/Phi-3-medium-4k-instruct"], "🔵", "#0078d4"),
    LLMProvider("gemma2", "Gemma 2 (Google)", "https://api.together.xyz/v1", "GEMMA2_API_KEY",
                "https://ai.google.dev/gemma", True, "免费额度", ["google/gemma-2-27b-it"], "💎", "#4285f4"),
    LLMProvider("qwen2-5", "Qwen 2.5 (Alibaba)", "https://api.siliconflow.cn/v1", "QWEN2_5_API_KEY",
                "https://siliconflow.cn/models", True, "免费额度", ["Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-7B-Instruct"], "🟢", "#615ced"),
    LLMProvider("deepseek-r1", "DeepSeek R1", "https://api.deepseek.com/v1", "DEEPSEEK_R1_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-reasoner", "deepseek-r1"], "🐳", "#4d6bfe"),
    LLMProvider("llama-3-3", "Llama 3.3 (Meta)", "https://api.together.xyz/v1", "LLAMA_3_3_API_KEY",
                "https://huggingface.co/meta-llama", True, "免费额度", ["meta-llama/Llama-3.3-70B-Instruct"], "🦙", "#0668e1"),
    LLMProvider("mixtral", "Mixtral (Mistral)", "https://api.mistral.ai/v1", "MIXTRAL_API_KEY",
                "https://mistral.ai/news/mixtral-of-experts", True, "免费额度", ["mistralai/Mixtral-8x7B-Instruct-v0.1"], "🟣", "#ff7000"),
    LLMProvider("yi-vision", "Yi Vision", "https://api.lingyiwanwu.com/v1", "YI_VISION_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-vision"], "👁️", "#00b4d8"),
    LLMProvider("glm-vision", "GLM-4V", "https://open.bigmodel.cn/api/paas/v4", "GLM_VISION_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4v-plus", "glm-4v"], "👁️", "#3859ff"),
    LLMProvider("qwen-vl", "Qwen-VL", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN_VL_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen-vl-max", "qwen-vl-plus"], "👁️", "#615ced"),
    LLMProvider("internvl", "InternVL", "https://api.siliconflow.cn/v1", "INTERNVL_API_KEY",
                "https://siliconflow.cn/models", True, "免费额度", ["OpenGVLab/InternVL2-Llama3-76B"], "👁️", "#7c3aed"),
    LLMProvider("minicpm", "MiniCPM", "https://api.siliconflow.cn/v1", "MINICPM_API_KEY",
                "https://github.com/OpenBMB/MiniCPM", True, "免费额度", ["openbmb/MiniCPM-Llama3-V-2_5"], "🟦", "#1e3a8a"),
    LLMProvider("internlm", "InternLM", "https://api.siliconflow.cn/v1", "INTERNLM_API_KEY",
                "https://github.com/InternLM/InternLM", True, "免费额度", ["internlm/internlm2_5-7b-chat"], "🟢", "#10b981"),
    LLMProvider("yi-34b", "Yi-34B", "https://api.lingyiwanwu.com/v1", "YI_34B_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-34b-chat"], "1️⃣", "#00b4d8"),
    LLMProvider("baichuan2", "Baichuan2", "https://api.baichuan-ai.com/v1", "BAICHUAN2_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan2-Turbo", "Baichuan2-13B-Chat"], "🏔️", "#0d9488"),
    LLMProvider("aquila", "Aquila (智源)", "https://api.siliconflow.cn/v1", "AQUILA_API_KEY",
                "https://github.com/FlagAlpha/Aquila2", True, "免费额度", ["BAAI/AquilaChat2-34B"], "🦅", "#1e40af"),
    LLMProvider("skywork", "Skywork (昆仑)", "https://api.tiangong.cn/v1", "SKYWORK_API_KEY",
                "https://tiangong.kunlun.com", True, "免费额度", ["skywork-13b"], "⛰️", "#ff5722"),
    LLMProvider("yi-large-rag", "Yi Large RAG", "https://api.lingyiwanwu.com/v1", "YI_LARGE_RAG_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large-rag"], "1️⃣", "#00b4d8"),
    LLMProvider("chatglm", "ChatGLM", "https://open.bigmodel.cn/api/paas/v4", "CHATGLM_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["chatglm_pro", "chatglm_std"], "✨", "#3859ff"),
    LLMProvider("glm-zero", "GLM Zero", "https://open.bigmodel.cn/api/paas/v4", "GLM_ZERO_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-zero-preview"], "0️⃣", "#3859ff"),
    LLMProvider("ernie-speed", "ERNIE Speed", "https://qianfan.baidubce.com/v2", "ERNIE_SPEED_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-speed-128k", "ernie-speed-8k"], "🟦", "#2932e1"),
    LLMProvider("ernie-lite", "ERNIE Lite", "https://qianfan.baidubce.com/v2", "ERNIE_LITE_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-lite-8k", "ernie-lite-pro-128k"], "🟦", "#2932e1"),
    LLMProvider("qwen-long", "Qwen Long", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN_LONG_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen-long"], "🟢", "#615ced"),
    LLMProvider("qwen3", "Qwen 3", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-235b-a22b", "qwen3-32b"], "🟢", "#615ced"),
    LLMProvider("doubao-vision", "Doubao Vision", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_VISION_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-vision-pro", "doubao-vision-lite"], "🌋", "#ff5a5f"),
    LLMProvider("doubao-pro", "Doubao Pro", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_PRO_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-pro-256k", "doubao-pro-128k"], "🌋", "#ff5a5f"),
    LLMProvider("minimax-abab", "MiniMax abab6", "https://api.minimax.chat/v1", "MINIMAX_ABAB_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["abab6-chat", "abab5.5-chat"], "🎯", "#ff6b6b"),
    LLMProvider("minimax-vision", "MiniMax Vision", "https://api.minimax.chat/v1", "MINIMAX_VISION_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["abab6.5s-vision"], "👁️", "#ff6b6b"),
    LLMProvider("spark-vision", "Spark Vision", "https://spark-api-open.xf-yun.com/v1", "SPARK_VISION_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["spark-v4"], "🔥", "#c41e3a"),
    LLMProvider("spark-max", "Spark Max", "https://spark-api-open.xf-yun.com/v1", "SPARK_MAX_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["generalv3.5-max", "spark-max-32k"], "🔥", "#c41e3a"),
    LLMProvider("hunyuan-vision", "Hunyuan Vision", "https://api.hunyuan.cloud.tencent.com/v1", "HUNYUAN_VISION_API_KEY",
                "https://cloud.tencent.com/document/product/1729", True, "免费额度", ["hunyuan-vision"], "🌀", "#0052d9"),
    LLMProvider("hunyuan-turbo", "Hunyuan Turbo", "https://api.hunyuan.cloud.tencent.com/v1", "HUNYUAN_TURBO_API_KEY",
                "https://cloud.tencent.com/document/product/1729", True, "免费额度", ["hunyuan-turbo", "hunyuan-turbo-256k"], "🌀", "#0052d9"),
    LLMProvider("baichuan-navigator", "Baichuan Navigator", "https://api.baichuan-ai.com/v1", "BAICHUAN_NAVIGATOR_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-Navigator-T1", "Baichuan-Navigator-T2"], "🏔️", "#0d9488"),
    LLMProvider("step-2", "Step-2", "https://api.stepfun.com/v1", "STEP_2_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-2-16k", "step-2-mini"], "⭐", "#7c3aed"),
    LLMProvider("step-1v", "Step-1V", "https://api.stepfun.com/v1", "STEP_1V_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-1v-32k", "step-1v-8k"], "👁️", "#7c3aed"),
    LLMProvider("yi-lightning", "Yi Lightning", "https://api.lingyiwanwu.com/v1", "YI_LIGHTNING_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-lightning", "yi-lightning-lite"], "⚡", "#00b4d8"),
    LLMProvider("glm-4-airx", "GLM-4 AirX", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_AIRX_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4-airx"], "✨", "#3859ff"),
    LLMProvider("glm-4-flashx", "GLM-4 FlashX", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_FLASHX_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "完全免费", ["glm-4-flashx"], "⚡", "#3859ff"),
    LLMProvider("glm-4-long", "GLM-4 Long", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_LONG_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4-long"], "📏", "#3859ff"),
    LLMProvider("deepseek-v3-api", "DeepSeek V3 API", "https://api.deepseek.com/v1", "DEEPSEEK_V3_API_KEY_2",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-chat", "deepseek-v3"], "🐳", "#4d6bfe"),
    LLMProvider("moonshot-vision", "Moonshot Vision", "https://api.moonshot.cn/v1", "MOONSHOT_VISION_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["moonshot-v1-32k-vision", "moonshot-v1-8k-vision"], "👁️", "#000000"),
    LLMProvider("kimi-k2", "Kimi K2", "https://api.moonshot.cn/v1", "KIMI_K2_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["kimi-k2-0905-preview", "kimi-k2-1205"], "🌙", "#000000"),
    LLMProvider("qwen3-coder", "Qwen3 Coder", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_CODER_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-coder-plus", "qwen3-coder-mini"], "💻", "#615ced"),
    LLMProvider("doubao-seed", "Doubao Seed", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6", "doubao-seed-1-6-250615"], "🌱", "#ff5a5f"),
    LLMProvider("glm-4-6", "GLM-4.6", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_6_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.6", "glm-4.6-air"], "✨", "#3859ff"),
    LLMProvider("glm-4-5", "GLM-4.5", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_5_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.5", "glm-4.5-air"], "✨", "#3859ff"),
    LLMProvider("ernie-5", "ERNIE 5.0", "https://qianfan.baidubce.com/v2", "ERNIE_5_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-5.0-128k", "ernie-5.0-turbo"], "🟦", "#2932e1"),
    LLMProvider("ernie-x1", "ERNIE X1", "https://qianfan.baidubce.com/v2", "ERNIE_X1_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-x1-turbo-128k", "ernie-x1-turbo-32k"], "🟦", "#2932e1"),
    LLMProvider("spark-4", "Spark 4.0", "https://spark-api-open.xf-yun.com/v1", "SPARK_4_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["spark-4.0-ultra", "spark-4.0-turbo"], "🔥", "#c41e3a"),
    LLMProvider("minimax-m1", "MiniMax M1", "https://api.minimax.chat/v1", "MINIMAX_M1_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-M1", "MiniMax-M1-80k"], "🎯", "#ff6b6b"),
    LLMProvider("minimax-text-01", "MiniMax Text 01", "https://api.minimax.chat/v1", "MINIMAX_TEXT_01_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-Text-01"], "🎯", "#ff6b6b"),
    LLMProvider("baichuan-m1", "Baichuan M1", "https://api.baichuan-ai.com/v1", "BAICHUAN_M1_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-M1-14B", "Baichuan-M1-32B"], "🏔️", "#0d9488"),
    LLMProvider("qwen3-coder-plus", "Qwen3 Coder Plus", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_CODER_PLUS_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-coder-plus", "qwen3-coder-plus-2025-09-13"], "💻", "#615ced"),
    LLMProvider("doubao-seed-coder", "Doubao Seed Coder", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_CODER_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-coder", "doubao-seed-coder-1-6"], "💻", "#ff5a5f"),
    LLMProvider("glm-4-5v", "GLM-4.5V", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_5V_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.5v", "glm-4.5v-flash"], "👁️", "#3859ff"),
    LLMProvider("glm-4-6v", "GLM-4.6V", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_6V_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.6v"], "👁️", "#3859ff"),
    LLMProvider("kimi-thinking", "Kimi Thinking", "https://api.moonshot.cn/v1", "KIMI_THINKING_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["kimi-thinking-preview"], "💭", "#000000"),
    LLMProvider("deepseek-v3-2", "DeepSeek V3.2", "https://api.deepseek.com/v1", "DEEPSEEK_V3_2_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-chat", "deepseek-v3-0324"], "🐳", "#4d6bfe"),
    LLMProvider("qwen3-235b", "Qwen3 235B", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_235B_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-235b-a22b-instruct"], "🟢", "#615ced"),
    LLMProvider("qwen3-32b", "Qwen3 32B", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_32B_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-32b-instruct"], "🟢", "#615ced"),
    LLMProvider("qwen3-30b", "Qwen3 30B", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_30B_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-30b-a3b-instruct"], "🟢", "#615ced"),
    LLMProvider("qwen3-coder-480", "Qwen3 Coder 480B", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_CODER_480_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-coder-480b-a35b-instruct"], "💻", "#615ced"),
    LLMProvider("doubao-seed-1-6", "Doubao Seed 1.6", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_1_6_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6-250615"], "🌱", "#ff5a5f"),
    LLMProvider("doubao-seed-1-6-thinking", "Doubao Seed 1.6 Thinking", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_1_6_THINKING_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6-thinking-250615"], "💭", "#ff5a5f"),
    LLMProvider("doubao-seed-1-6-thinking-250615", "Doubao Seed 1.6 Thinking 250615", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_1_6_THINKING_250615_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6-thinking-250615"], "💭", "#ff5a5f"),
    LLMProvider("glm-4-6-thinking", "GLM-4.6 Thinking", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_6_THINKING_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.6-thinking"], "💭", "#3859ff"),
    LLMProvider("glm-4-5-thinking", "GLM-4.5 Thinking", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_5_THINKING_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.5-thinking"], "💭", "#3859ff"),
    LLMProvider("glm-4-5-air", "GLM-4.5 Air", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_5_AIR_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.5-air"], "✨", "#3859ff"),
    LLMProvider("ernie-4-5-turbo", "ERNIE 4.5 Turbo", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_TURBO_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-turbo-128k", "ernie-4.5-turbo-32k"], "🟦", "#2932e1"),
    LLMProvider("ernie-4-5-turbo-vl", "ERNIE 4.5 Turbo VL", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_TURBO_VL_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-turbo-vl"], "👁️", "#2932e1"),
    LLMProvider("ernie-4-5-turbo-128k", "ERNIE 4.5 Turbo 128K", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_TURBO_128K_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-turbo-128k"], "🟦", "#2932e1"),
    LLMProvider("ernie-4-5-vl", "ERNIE 4.5 VL", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_VL_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-vl-pretrained"], "👁️", "#2932e1"),
    LLMProvider("spark-4-0-ultra", "Spark 4.0 Ultra", "https://spark-api-open.xf-yun.com/v1", "SPARK_4_0_ULTRA_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["spark-4.0-ultra"], "🔥", "#c41e3a"),
    LLMProvider("minimax-m2", "MiniMax M2", "https://api.minimax.chat/v1", "MINIMAX_M2_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-M2"], "🎯", "#ff6b6b"),
    LLMProvider("minimax-m2-1206", "MiniMax M2 1206", "https://api.minimax.chat/v1", "MINIMAX_M2_1206_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-M2-1206"], "🎯", "#ff6b6b"),
    LLMProvider("baichuan-m2", "Baichuan M2", "https://api.baichuan-ai.com/v1", "BAICHUAN_M2_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-M2"], "🏔️", "#0d9488"),
    LLMProvider("baichuan-m2-1206", "Baichuan M2 1206", "https://api.baichuan-ai.com/v1", "BAICHUAN_M2_1206_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-M2-1206"], "🏔️", "#0d9488"),
    LLMProvider("step-3", "Step-3", "https://api.stepfun.com/v1", "STEP_3_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-3"], "⭐", "#7c3aed"),
    LLMProvider("yi-large-rag-preview", "Yi Large RAG Preview", "https://api.lingyiwanwu.com/v1", "YI_LARGE_RAG_PREVIEW_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large-rag-preview"], "1️⃣", "#00b4d8"),
    LLMProvider("yi-large-turbo", "Yi Large Turbo", "https://api.lingyiwanwu.com/v1", "YI_LARGE_TURBO_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large-turbo"], "1️⃣", "#00b4d8"),
    LLMProvider("kimi-k2-thinking", "Kimi K2 Thinking", "https://api.moonshot.cn/v1", "KIMI_K2_THINKING_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["kimi-k2-thinking-preview"], "💭", "#000000"),
    LLMProvider("deepseek-r2", "DeepSeek R2", "https://api.deepseek.com/v1", "DEEPSEEK_R2_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-r2"], "🐳", "#4d6bfe"),
    LLMProvider("qwen3-thinking", "Qwen3 Thinking", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_THINKING_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-thinking-preview"], "💭", "#615ced"),
    LLMProvider("doubao-seed-1-6-thinking-250615-preview", "Doubao Seed 1.6 Thinking Preview", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_1_6_THINKING_250615_PREVIEW_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6-thinking-250615-preview"], "💭", "#ff5a5f"),
    LLMProvider("glm-4-6-thinking-250615", "GLM-4.6 Thinking 250615", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_6_THINKING_250615_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.6-thinking-250615"], "💭", "#3859ff"),
    LLMProvider("ernie-4-5-turbo-128k-thinking", "ERNIE 4.5 Turbo 128K Thinking", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_TURBO_128K_THINKING_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-turbo-128k-thinking"], "💭", "#2932e1"),
    LLMProvider("spark-4-0-ultra-thinking", "Spark 4.0 Ultra Thinking", "https://spark-api-open.xf-yun.com/v1", "SPARK_4_0_ULTRA_THINKING_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["spark-4.0-ultra-thinking"], "💭", "#c41e3a"),
    LLMProvider("minimax-m2-thinking", "MiniMax M2 Thinking", "https://api.minimax.chat/v1", "MINIMAX_M2_THINKING_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-M2-thinking"], "💭", "#ff6b6b"),
    LLMProvider("baichuan-m2-thinking", "Baichuan M2 Thinking", "https://api.baichuan-ai.com/v1", "BAICHUAN_M2_THINKING_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-M2-thinking"], "💭", "#0d9488"),
    LLMProvider("step-3-thinking", "Step-3 Thinking", "https://api.stepfun.com/v1", "STEP_3_THINKING_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-3-thinking"], "💭", "#7c3aed"),
    LLMProvider("yi-large-thinking", "Yi Large Thinking", "https://api.lingyiwanwu.com/v1", "YI_LARGE_THINKING_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large-thinking"], "💭", "#00b4d8"),
    LLMProvider("kimi-k2-1206-thinking", "Kimi K2 1206 Thinking", "https://api.moonshot.cn/v1", "KIMI_K2_1206_THINKING_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["kimi-k2-1206-thinking"], "💭", "#000000"),
    LLMProvider("deepseek-r2-thinking", "DeepSeek R2 Thinking", "https://api.deepseek.com/v1", "DEEPSEEK_R2_THINKING_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-r2-thinking"], "💭", "#4d6bfe"),
    LLMProvider("qwen3-thinking-250615", "Qwen3 Thinking 250615", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_THINKING_250615_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-thinking-250615"], "💭", "#615ced"),
    LLMProvider("doubao-seed-1-6-thinking-250615-thinking", "Doubao Seed 1.6 Thinking 250615 Thinking", "https://ark.cn-beijing.volces.com/api/v3", "DOUBAO_SEED_1_6_THINKING_250615_THINKING_API_KEY",
                "https://www.volcengine.com/docs/82379", True, "免费额度", ["doubao-seed-1-6-thinking-250615-thinking"], "💭", "#ff5a5f"),
    LLMProvider("glm-4-6-thinking-250615-thinking", "GLM-4.6 Thinking 250615 Thinking", "https://open.bigmodel.cn/api/paas/v4", "GLM_4_6_THINKING_250615_THINKING_API_KEY",
                "https://open.bigmodel.cn/dev/api", True, "送 2000 万 token", ["glm-4.6-thinking-250615-thinking"], "💭", "#3859ff"),
    LLMProvider("ernie-4-5-turbo-128k-thinking-250615", "ERNIE 4.5 Turbo 128K Thinking 250615", "https://qianfan.baidubce.com/v2", "ERNIE_4_5_TURBO_128K_THINKING_250615_API_KEY",
                "https://cloud.baidu.com/doc/WENXINWORKSHOP", True, "免费额度", ["ernie-4.5-turbo-128k-thinking-250615"], "💭", "#2932e1"),
    LLMProvider("spark-4-0-ultra-thinking-250615", "Spark 4.0 Ultra Thinking 250615", "https://spark-api-open.xf-yun.com/v1", "SPARK_4_0_ULTRA_THINKING_250615_API_KEY",
                "https://www.xfyun.cn/doc", True, "免费额度", ["spark-4.0-ultra-thinking-250615"], "💭", "#c41e3a"),
    LLMProvider("minimax-m2-thinking-250615", "MiniMax M2 Thinking 250615", "https://api.minimax.chat/v1", "MINIMAX_M2_THINKING_250615_API_KEY",
                "https://platform.minimaxi.com/docs", True, "送 15 元额度", ["MiniMax-M2-thinking-250615"], "💭", "#ff6b6b"),
    LLMProvider("baichuan-m2-thinking-250615", "Baichuan M2 Thinking 250615", "https://api.baichuan-ai.com/v1", "BAICHUAN_M2_THINKING_250615_API_KEY",
                "https://platform.baichuan-ai.com/docs", True, "新用户免费", ["Baichuan-M2-thinking-250615"], "💭", "#0d9488"),
    LLMProvider("step-3-thinking-250615", "Step-3 Thinking 250615", "https://api.stepfun.com/v1", "STEP_3_THINKING_250615_API_KEY",
                "https://platform.stepfun.com/docs", True, "新用户免费", ["step-3-thinking-250615"], "💭", "#7c3aed"),
    LLMProvider("yi-large-thinking-250615", "Yi Large Thinking 250615", "https://api.lingyiwanwu.com/v1", "YI_LARGE_THINKING_250615_API_KEY",
                "https://platform.lingyiwanwu.com", True, "送 100 万 token", ["yi-large-thinking-250615"], "💭", "#00b4d8"),
    LLMProvider("kimi-k2-1206-thinking-250615", "Kimi K2 1206 Thinking 250615", "https://api.moonshot.cn/v1", "KIMI_K2_1206_THINKING_250615_API_KEY",
                "https://platform.moonshot.cn/docs", True, "送 15 元额度", ["kimi-k2-1206-thinking-250615"], "💭", "#000000"),
    LLMProvider("deepseek-r2-thinking-250615", "DeepSeek R2 Thinking 250615", "https://api.deepseek.com/v1", "DEEPSEEK_R2_THINKING_250615_API_KEY",
                "https://platform.deepseek.com", True, "送 500 万 token", ["deepseek-r2-thinking-250615"], "💭", "#4d6bfe"),
    LLMProvider("qwen3-thinking-250615-preview", "Qwen3 Thinking 250615 Preview", "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN3_THINKING_250615_PREVIEW_API_KEY",
                "https://help.aliyun.com/zh/dashscope", True, "新用户免费额度", ["qwen3-thinking-250615-preview"], "💭", "#615ced"),
]


def get_provider_by_id(provider_id: str) -> LLMProvider | None:
    """根据 id 查找供应商。"""
    for p in PROVIDERS:
        if p.id == provider_id:
            return p
    return None


def get_free_providers() -> list[LLMProvider]:
    """返回所有有免费额度的供应商。"""
    return [p for p in PROVIDERS if p.free_tier]


def provider_to_dict(p: LLMProvider, include_key: bool = False) -> dict:
    """将供应商转为字典（默认不暴露 api_key_env 的实际值）。

    不返回 icon 字段 — 前端统一无图标风格。
    """
    return {
        "id": p.id,
        "name": p.name,
        "base_url": p.base_url,
        "api_key_env": p.api_key_env if include_key else None,
        "has_api_key": _has_env(p.api_key_env),
        "docs_url": p.docs_url,
        "free_tier": p.free_tier,
        "free_tier_desc": p.free_tier_desc,
        "models": p.models,
        "region": getattr(p, "region", "intl"),
    }


def _has_env(env_name: str) -> bool:
    """检查环境变量是否已设置（不返回值）。"""
    import os
    return bool(os.environ.get(env_name))
