"""Core data types for Agents - Context, Plan, Artifact.

Inspired by Claude Code's Task system and OpenHands's State management.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class AgentRole(str, Enum):
    """Agent roles in the workflow."""

    REQUIREMENTS = "requirements"
    DESIGN = "design"
    FRONTEND = "frontend"
    BACKEND = "backend"
    TESTING = "testing"
    REVIEW = "review"
    DEPLOYMENT = "deployment"


class AgentStatus(str, Enum):
    """Execution status of an Agent."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class Context:
    """Shared context passed between Agents in a workflow.

    Contains user requirement, project metadata, intermediate outputs,
    and experience hints.
    """

    session_id: str
    project_id: str
    user_requirement: str

    # Agent outputs keyed by role
    agent_outputs: Dict[str, Any] = field(default_factory=dict)

    # Experience hints (used for error recovery)
    experience_hints: List[Dict[str, str]] = field(default_factory=list)

    # General metadata
    metadata: Dict[str, Any] = field(default_factory=dict)

    def set_output(self, agent_role: str, output: Any) -> None:
        """Set output from an Agent."""
        self.agent_outputs[agent_role] = output

    def get_output(self, agent_role: str) -> Optional[Any]:
        """Get output from a previous Agent."""
        return self.agent_outputs.get(agent_role)

    def add_hint(self, hint: str, source: str = "experience") -> None:
        """Add a hint/lesson for the current session."""
        self.experience_hints.append({"source": source, "content": hint})

    def to_dict(self) -> Dict[str, Any]:
        """Serialize context for logging/frontend."""
        return {
            "session_id": self.session_id,
            "project_id": self.project_id,
            "user_requirement": self.user_requirement,
            "agent_outputs": list(self.agent_outputs.keys()),
            "hints_count": len(self.experience_hints),
        }


@dataclass
class PlanStep:
    """A single step in an Agent's plan."""

    description: str
    tool: str  # Which tool to use
    parameters: Dict[str, Any] = field(default_factory=dict)
    expected_output: str = ""


@dataclass
class Plan:
    """Plan created by an Agent before execution."""

    agent_role: str
    summary: str
    steps: List[PlanStep] = field(default_factory=list)

    def add_step(self, description: str, tool: str, parameters: Dict[str, Any] = None) -> None:
        """Add a step to the plan."""
        self.steps.append(PlanStep(
            description=description,
            tool=tool,
            parameters=parameters or {},
        ))


@dataclass
class Artifact:
    """Output artifact generated by an Agent."""

    agent_role: str
    artifact_type: str  # e.g., "document", "code", "config"
    name: str
    content: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize artifact for frontend/storage."""
        return {
            "agent_role": self.agent_role,
            "type": self.artifact_type,
            "name": self.name,
            "content": self.content,
            "metadata": self.metadata,
        }
